# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PI3sFVWthKkbYWJSEs4RblwLkq5Q46Uw
"""

!pip install pydub

!apt-get update -qq
!apt-get install -y ffmpeg
!pip install diffusers transformers accelerate scipy

import torch
import os
from diffusers import StableDiffusionPipeline
import subprocess

os.makedirs("images", exist_ok=True)
os.makedirs("output", exist_ok=True)



course_data = {
    "topic": "Finance personnelle",
    "style": "cartoon",
    "tone": "fun",
    "language": "fr",
    "scenes": [
        {
            "title": "Bienvenue dans le monde de la finance",
            "content": "La finance personnelle, c’est apprendre à gérer ton argent intelligemment, même si tu débutes.",
            "duration": 8
        },
        {
            "title": "Pourquoi l’argent est important",
            "content": "L’argent te permet de payer tes besoins, réaliser tes projets et sécuriser ton avenir.",
            "duration": 8
        },
        {
            "title": "Revenus et dépenses",
            "content": "Tes revenus sont l’argent que tu gagnes, et tes dépenses sont l’argent que tu dépenses chaque jour.",
            "duration": 8
        },
        {
            "title": "Épargner, même un peu",
            "content": "Mettre de côté une petite somme régulièrement t’aide à faire face aux imprévus.",
            "duration": 8
        },
        {
            "title": "Éviter les dettes inutiles",
            "content": "Emprunter peut être utile, mais trop de dettes peuvent devenir un problème.",
            "duration": 8
        },
        {
            "title": "Investir pour le futur",
            "content": "Investir, c’est utiliser ton argent pour en gagner davantage avec le temps.",
            "duration": 8
        },
        {
            "title": "Objectifs financiers",
            "content": "Fixe-toi des objectifs simples comme acheter quelque chose ou économiser pour un projet.",
            "duration": 8
        },
        {
            "title": "Bravo, tu progresses",
            "content": "Félicitations ! Tu viens de faire tes premiers pas vers une meilleure gestion de ton argent.",
            "duration": 8
        }
    ]
}

from pydub import AudioSegment

def get_audio_duration(audio_path: str) -> float:
    audio = AudioSegment.from_file(audio_path)
    return audio.duration_seconds  # durée en secondes

!pip install gtts

import os
import uuid
import subprocess
from gtts import gTTS
import torch
from diffusers import StableDiffusionPipeline

# Charger Stable Diffusion UNE SEULE FOIS
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to("cuda")

def generate_course_video(course_data: dict) -> str:
    import os, uuid, subprocess
    from gtts import gTTS
    from pydub import AudioSegment

    os.makedirs("tmp/images", exist_ok=True)
    os.makedirs("tmp/audio", exist_ok=True)
    os.makedirs("output/videos", exist_ok=True)

    segments = []

    for idx, scene in enumerate(course_data["scenes"]):
        # 1️⃣ Génération image
        prompt = f"Cute cartoon, {scene['title']}, {scene['content']}"
        image = pipe(prompt, num_inference_steps=20).images[0]
        img_path = f"tmp/images/scene_{idx}.png"
        image.save(img_path)

        # 2️⃣ Génération audio GTTS
        audio_mp3 = f"tmp/audio/scene_{idx}.mp3"
        tts = gTTS(text=scene["content"], lang="fr")
        tts.save(audio_mp3)

        # 3️⃣ Convertir en wav
        audio_wav = audio_mp3.replace(".mp3", ".wav")
        subprocess.run(["ffmpeg", "-y", "-i", audio_mp3, audio_wav], check=True)

        # 4️⃣ Obtenir durée exacte
        audio_duration = AudioSegment.from_file(audio_wav).duration_seconds

        # 5️⃣ Créer segment vidéo pour cette scène
        segment_path = f"tmp/segment_{idx}.mp4"
        subprocess.run([
            "ffmpeg", "-y",
            "-loop", "1", "-i", img_path,
            "-i", audio_wav,
            "-c:v", "libx264",
            "-t", str(audio_duration),
            "-pix_fmt", "yuv420p",
            "-c:a", "aac",
            segment_path
        ], check=True)

        segments.append(segment_path)

    # 6️⃣ Concaténer tous les segments
    concat_file = "tmp/segments.txt"
    with open(concat_file, "w") as f:
        for seg in segments:
            f.write(f"file '{os.path.abspath(seg)}'\n")

    output_video = f"output/videos/course_{uuid.uuid4().hex}.mp4"
    subprocess.run([
        "ffmpeg", "-y", "-f", "concat", "-safe", "0",
        "-i", concat_file,
        "-c", "copy",
        output_video
    ], check=True)

    return output_video

!apt-get update -qq
!apt-get install -y espeak

video_path = generate_course_video(course_data)